apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: Instance
metadata:
  name: crossplane-mini-volume
spec:
  forProvider:
    region: us-east-1
    imageId: ami-09cd747c78a9add63
    instanceType: t2.medium
    blockDeviceMappings:
      - deviceName: /dev/sda1
        ebs:
          volumeSize: 40
    keyName: test2
    tags:
      - key: Name
        value: test-crossplane-minikube
    subnetIdRef:
      name: crossplane-subnet-1
    securityGroupRefs:
      - name: crossplane-security-group
  providerConfigRef:
    name: default
